{% set name = "pytransit" %}
{% set version = "2.7.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytransit-{{ version }}.tar.gz
  sha256: 3b027ecbc9dceb59b5c544909ca06433dd3bff944fac507816481fa4b8046ba0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - arviz
    - numpy >=2.0.0
    - scipy
    - pandas
    - xarray
    - tables
    - uncertainties
    - numba
    - astropy-base
    - matplotlib-base
    - tqdm
    - semantic_version
    - setuptools
    - deprecated
    - seaborn
    - emcee
    - pyopencl
    - corner
    - celerite
    - meepmeep >=0.8.0

test:
  imports:
    - pytransit
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Fast and painless exoplanet transit light curve modelling.
  license: GPL-2.0-only
  license_file: LICENSE
  home: https://github.com/hpparvi/PyTransit

extra:
  recipe-maintainers:
    - hpparvi
